// Mock data for IA v6 Channels module.
// Drives development before backend wiring; later swap to `api<T>()` calls.

import type {
  EndpointInbound,
  EndpointOutbound,
  LLMProvider,
  MCPServer,
  OAuthAuthorizedThirdParty,
  OAuthClient,
  RoutingRule,
  Skill,
} from "./types";

export const MOCK_LLM: LLMProvider[] = [
  {
    id: "p_openai",
    name: "OpenAI · 主生产",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    model: "gpt-4o-mini",
    isDefault: true,
    status: "connected",
    lastTestedAt: "2026-07-08T03:21:00Z",
    hasApiKey: true,
    latencyMs: 612,
  },
  {
    id: "p_anthropic",
    name: "Anthropic · Claude",
    type: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    model: "claude-3-5-sonnet",
    isDefault: false,
    status: "expired",
    lastTestedAt: "2026-07-06T11:02:00Z",
    hasApiKey: true,
    latencyMs: 1840,
  },
  {
    id: "p_google",
    name: "Google · Gemini",
    type: "google",
    baseUrl: "https://generativelanguage.googleapis.com/v1",
    model: "gemini-1.5-pro",
    isDefault: false,
    status: "needs-api-key",
    lastTestedAt: null,
    hasApiKey: false,
    latencyMs: null,
  },
  {
    id: "p_local",
    name: "本地 · Ollama",
    type: "local",
    baseUrl: "http://127.0.0.1:11434/v1",
    model: "qwen2.5-coder:7b",
    isDefault: false,
    status: "connected",
    lastTestedAt: "2026-07-08T02:45:00Z",
    hasApiKey: true,
    latencyMs: 92,
  },
  {
    id: "p_deepseek",
    name: "DeepSeek · 代码专用",
    type: "deepseek",
    baseUrl: "https://api.deepseek.com/v1",
    model: "deepseek-coder",
    isDefault: false,
    status: "error",
    lastTestedAt: "2026-07-07T22:11:00Z",
    hasApiKey: true,
    latencyMs: 4100,
  },
];

export const MOCK_SKILLS: Skill[] = [
  {
    id: "sk_pdf_extract",
    name: "pdf.extract",
    description: "从 PDF 文档抽取结构化文本与表格",
    source: "built-in",
    enabled: true,
    tags: ["document", "ocr"],
    installedAt: "2026-06-01",
  },
  {
    id: "sk_excel_parse",
    name: "excel.parse",
    description: "解析 Excel 工作表并按 sheet 输出",
    source: "built-in",
    enabled: true,
    tags: ["spreadsheet"],
    installedAt: "2026-06-01",
  },
  {
    id: "sk_github_issue",
    name: "github.issue",
    description: "读取与创建 GitHub issue (需 GH_TOKEN)",
    source: "github",
    enabled: true,
    tags: ["github", "external"],
    installedAt: "2026-06-12",
  },
  {
    id: "sk_feishu_msg",
    name: "feishu.message",
    description: "发送飞书消息与互动卡片",
    source: "built-in",
    enabled: true,
    tags: ["feishu", "messaging"],
    installedAt: "2026-06-01",
  },
  {
    id: "sk_sql_query",
    name: "sql.query",
    description: "在白名单表上执行受限 SQL",
    source: "custom",
    enabled: false,
    tags: ["database", "readonly"],
    installedAt: "2026-07-02",
  },
  {
    id: "sk_local_summarize",
    name: "local.summarize",
    description: "本地化摘要,避免外发敏感片段",
    source: "local",
    enabled: true,
    tags: ["nlp", "privacy"],
    installedAt: "2026-06-20",
  },
];

export const MOCK_MCP: MCPServer[] = [
  {
    id: "m_filesystem",
    name: "filesystem",
    transport: "stdio",
    url: "npx -y @modelcontextprotocol/server-filesystem /workspace",
    auth: null,
    status: "running",
    toolCount: 11,
  },
  {
    id: "m_pg",
    name: "postgres-readonly",
    transport: "stdio",
    url: "npx -y @modelcontextprotocol/server-postgres postgresql://readonly@db/panmira",
    auth: null,
    status: "running",
    toolCount: 6,
  },
  {
    id: "m_http_remote",
    name: "internal-tools-http",
    transport: "http",
    url: "http://10.0.4.21:7800/mcp",
    auth: "Bearer ***",
    status: "stopped",
    toolCount: 0,
  },
  {
    id: "m_sse_browser",
    name: "browser-sse",
    transport: "sse",
    url: "http://10.0.4.22:7801/sse",
    auth: null,
    status: "error",
    toolCount: 0,
  },
];

export const MOCK_OUTBOUND: EndpointOutbound[] = [
  {
    id: "ep_ob_xuanjian",
    channel: "feishu",
    botName: "玄鉴",
    webhookUrl: "https://open.feishu.cn/open-apis/bot/v2/hook/***",
    status: "active",
    purpose: "outbound",
    remark: "主风控 bot",
  },
  {
    id: "ep_ob_xinyan",
    channel: "dingtalk",
    botName: "信言",
    webhookUrl: "https://oapi.dingtalk.com/robot/send?access_token=***",
    status: "active",
    purpose: "outbound",
    remark: "代码评审通知",
  },
  {
    id: "ep_ob_shoujing",
    channel: "wechatwork",
    botName: "守静",
    webhookUrl: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=***",
    status: "paused",
    purpose: "outbound",
    remark: "企业微信日报",
  },
];

export const MOCK_INBOUND: EndpointInbound[] = [
  {
    id: "ep_in_feishu_event",
    name: "feishu.event",
    callbackUrl: "https://api.deepx.fun/inbound/feishu/event",
    allowedMethods: ["POST"],
    apiVersion: "v1",
    rateLimit: "60/min",
    status: "active",
  },
  {
    id: "ep_in_dingtalk_event",
    name: "dingtalk.event",
    callbackUrl: "https://api.deepx.fun/inbound/dingtalk/event",
    allowedMethods: ["POST"],
    apiVersion: "v1",
    rateLimit: "60/min",
    status: "active",
  },
  {
    id: "ep_in_webhook_generic",
    name: "webhook.generic",
    callbackUrl: "https://api.deepx.fun/inbound/webhook/{token}",
    allowedMethods: ["POST", "PUT"],
    apiVersion: "v1",
    rateLimit: "120/min",
    status: "active",
  },
];

export const MOCK_OAUTH_AUTHORIZED: OAuthAuthorizedThirdParty[] = [
  {
    id: "oa_atlas",
    name: "Atlas CRM",
    scopes: ["profile", "tasks.read"],
    authorizedAt: "2026-06-15",
    status: "active",
  },
  {
    id: "oa_nebula",
    name: "Nebula Sheets",
    scopes: ["files.read"],
    authorizedAt: "2026-05-22",
    status: "expired",
  },
];

export const MOCK_OAUTH_CLIENTS: OAuthClient[] = [
  {
    id: "oc_internal_bot",
    clientId: "panmira_bot_studio",
    name: "Bot Studio (internal)",
    redirectUris: ["https://studio.deepx.fun/oauth/callback"],
    status: "active",
    createdAt: "2026-06-01",
    scopes: ["agent.read", "agent.write"],
  },
  {
    id: "oc_partner_x",
    clientId: "x_partner_demo",
    name: "Partner X Demo",
    redirectUris: ["https://partner.example.com/oauth/callback"],
    status: "disabled",
    createdAt: "2026-06-29",
    scopes: ["agent.read"],
  },
];

export const MOCK_ROUTING: RoutingRule[] = [
  {
    id: "r1",
    botId: "b_xuanjian",
    botName: "玄鉴",
    priority: 1,
    condition: "channel == 'feishu' && intent == 'risk'",
    destination: "agent.xuanjian",
    enabled: true,
  },
  {
    id: "r2",
    botId: "b_xinyan",
    botName: "信言",
    priority: 2,
    condition: "channel == 'dingtalk' && tag == 'code-review'",
    destination: "agent.xinyan",
    enabled: true,
  },
  {
    id: "r3",
    botId: "b_shoujing",
    botName: "守静",
    priority: 3,
    condition: "channel == 'wechatwork'",
    destination: "agent.shoujing",
    enabled: false,
  },
  {
    id: "r4",
    botId: "b_default",
    botName: "默认回退",
    priority: 99,
    condition: "*",
    destination: "agent.fallback",
    enabled: true,
  },
];